/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            "colors": {
                "on-primary-container": "#ccffcb",
                "inverse-primary": "#88d98f",
                "surface-container-low": "#eff4ff",
                "inverse-on-surface": "#eaf1ff",
                "surface-tint": "#1a6c30",
                "error": "#ba1a1a",
                "outline": "#707a6e",
                "on-secondary-fixed": "#001b3d",
                "tertiary-fixed-dim": "#ffb95f",
                "on-secondary": "#ffffff",
                "surface-variant": "#d3e4fe",
                "error-container": "#ffdad6",
                "on-error": "#ffffff",
                "surface-container-highest": "#d3e4fe",
                "secondary-container": "#64a1ff",
                "on-secondary-container": "#003670",
                "primary": "#0c6328",
                "primary-fixed": "#a3f6a9",
                "outline-variant": "#bfc9bb",
                "surface": "#f8f9ff",
                "on-tertiary-container": "#fff0e3",
                "on-tertiary-fixed-variant": "#653e00",
                "on-primary-fixed": "#002108",
                "on-tertiary": "#ffffff",
                "on-primary": "#ffffff",
                "surface-container": "#e5eeff",
                "background": "#f8f9ff",
                "surface-container-lowest": "#ffffff",
                "secondary-fixed-dim": "#a9c7ff",
                "on-surface": "#0b1c30",
                "primary-container": "#2e7d3e",
                "tertiary-container": "#9b6200",
                "primary-fixed-dim": "#88d98f",
                "inverse-surface": "#213145",
                "secondary": "#005db7",
                "surface-container-high": "#dce9ff",
                "tertiary": "#7a4c00",
                "surface-dim": "#cbdbf5",
                "on-secondary-fixed-variant": "#00468c",
                "secondary-fixed": "#d6e3ff",
                "on-tertiary-fixed": "#2a1700",
                "on-surface-variant": "#40493f",
                "on-primary-fixed-variant": "#00531e",
                "surface-bright": "#f8f9ff",
                "on-error-container": "#93000a",
                "tertiary-fixed": "#ffddb8",
                "on-background": "#0b1c30"
            },
            "fontFamily": {
                "headline": ["Manrope", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"]
            }
        },
    },
    plugins: [],
}
